name: Deploy

on:
  workflow_dispatch:
  push:
    branches: ["main"]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ruby-version: 2.6

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.ruby-version }}

      - name: Cache gems
        uses: actions/cache@v4
        with:
          path: vendor/bundle
          key: gems-${{ runner.os }}-${{ env.ruby-version }}-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            gems-${{ runner.os }}-${{ env.ruby-version }}-
            gems-${{ runner.os }}-

      - name: Install dependencies
        run: |
          bundle config set deployment 'true'
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3

      - name: Build site
        run: bundle exec middleman build

      - name: Debug: List build directory
        run: |
          echo '=== 列出 build 目录内容 ==='
          ls -alh build || echo 'build 目录不存在'
          echo '=== 计算 build 目录大小 ==='
          du -sh build || echo '无法计算 build 目录大小'

      - name: Configure CNAME
        run: |
          cd build
          echo 'docs.coincall.com' > CNAME

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          name: github-pages
          path: build

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v3
        with:
          artifact_name: github-pages
