name: Deploy

on:
  workflow_dispatch:
  push:
    branches: ["main"]
    
permissions:
  contents: read
  pages: write
  id-token: write
  
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ruby-version: 2.6

    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.ruby-version }}

      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: gems-${{ runner.os }}-${{ env.ruby-version }}-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            gems-${{ runner.os }}-${{ env.ruby-version }}-
            gems-${{ runner.os }}-

      - run: bundle config set deployment 'true'
      - name: bundle install
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
          
      - run: bundle exec middleman build
      - run: |
          cd build
          echo 'docs.coincall.com' > CNAME
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          name: my-artifact-${{ matrix.runs-on }}
          path: ./build

  # Deployment job
  deploy:
    needs: build

    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
